export const topFighters = [
  {
    id: "darya-volkova",
    name: "Darya Volkova",
    nickname: "The Switch",
    country: "Azerbaijan",
    flag: "🇦🇿",
    weightClass: "Flyweight",
    record: "12-3-1",
    points: 1840,
    rank: 1,
    status: "Pro",
    federation: "AMMAF",
    streak: "W4",
    image: "/assets/fighter-portrait.png",
  },
  {
    id: "marco-santos",
    name: "Marco Santos",
    nickname: "North Star",
    country: "Brazil",
    flag: "🇧🇷",
    weightClass: "Bantamweight",
    record: "9-1-0",
    points: 1715,
    rank: 2,
    status: "Pro",
    federation: "CBMMA",
    streak: "W6",
    image: "/assets/fighter-portrait.png",
  },
  {
    id: "elias-kane",
    name: "Elias Kane",
    nickname: "The Ledger",
    country: "United States",
    flag: "🇺🇸",
    weightClass: "Welterweight",
    record: "8-2-0",
    points: 1520,
    rank: 3,
    status: "Amateur",
    federation: null,
    streak: "W2",
    image: "/assets/fighter-portrait.png",
  },
];

export const featuredFights = [
  {
    title: "Flyweight title eliminator",
    date: "Jun 18",
    location: "Baku",
    fighters: "Volkova vs. Imanova",
    stake: "Winner takes #1 regional Pro seed",
  },
  {
    title: "Amateur rankings clash",
    date: "Jun 22",
    location: "Warsaw",
    fighters: "Kane vs. Nowak",
    stake: "Top 10 Welterweight movement",
  },
];

export const profile = {
  name: "Darya Volkova",
  nickname: "The Switch",
  country: "Azerbaijan",
  flag: "🇦🇿",
  city: "Baku",
  gym: "Caspian Combat Lab",
  weightClass: "Flyweight",
  status: "Pro",
  federation: "Azerbaijan MMA Federation",
  record: { wins: 12, losses: 3, draws: 1 },
  points: 1840,
  countryRank: 1,
  weightRank: 4,
  image: "/assets/fighter-portrait.png",
  cover: "/assets/hero-arena.png",
  bio: "Pressure striker with a southpaw switch, active cage wrestling, and a verified federation record dating back to 2021.",
  socials: {
    instagram: "@darya.switch",
    youtube: "Darya Volkova MMA",
  },
  methods: [
    { label: "KO/TKO", value: 5, color: "bg-blood" },
    { label: "Submission", value: 4, color: "bg-white" },
    { label: "Decision", value: 3, color: "bg-zinc-500" },
  ],
  history: [
    {
      date: "2026-04-11",
      opponent: "Leyla Imanova",
      event: "Caspian Fight Night 14",
      result: "Win",
      method: "Decision",
      round: 3,
      time: "5:00",
    },
    {
      date: "2026-02-02",
      opponent: "Mira Petrova",
      event: "Eurasia MMA Open",
      result: "Win",
      method: "Submission",
      round: 2,
      time: "3:18",
    },
    {
      date: "2025-11-19",
      opponent: "Aylin Demir",
      event: "IMMAF Regional Series",
      result: "Loss",
      method: "Decision",
      round: 3,
      time: "5:00",
    },
    {
      date: "2025-09-07",
      opponent: "Nika Orlova",
      event: "Black Sea Combat",
      result: "Win",
      method: "KO/TKO",
      round: 1,
      time: "2:44",
    },
  ],
};
